---
platform: linux
image_resource:
  type: docker-image
  source: {repository: microsoft/azure-cli, tag: 2.0.60}

inputs:
  - name: scripts-source
  - name: source-code

run:
  path: scripts-source/tasks/deploy_solution.sh