---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.3.9-jdk-8}

inputs:
  - name: source-code
  - name: scripts-source

outputs:
  - name: artifacts

run:
  path: scripts-source/tasks/maven-build.sh