---
platform: linux
image_resource:
  type: docker-image
  source: {repository: microsoft/iotedgedev, tag: latest}

inputs:
  - name: source-code
  - name: scripts-source
  - name: artifacts

run:
  path: scripts-source/tasks/push-image.sh