---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/matocha-m/iot-edge-test.git
    branch: master
    private_key: ((git.private_key))
- name: scripts-source
  type: git
  source:
    uri: https://github.com/matocha-m/test1.git
    branch: master
    private_key: ((git.private_key))

- name: trigger
  type: time


jobs:
- name: build-project2
  public: true
  plan:
  - get: source-code
    trigger: true
  - get: scripts-source
  - task: maven-build
    file: scripts-source/tasks/maven-build.yml
    params:
      APPNAME: test-iot
      MODULE_NAME: ((module-name))
  - task: push-image
    privileged: true
    file: scripts-source/tasks/push-image.yml
    params:
      MODULE_NAME: ((module-name))
      CONTAINER_REGISTRY_USERNAME_cconregistry: ((registery-username))
      CONTAINER_REGISTRY_PASSWORD_cconregistry: ((registery-password))
  - put: trigger
  
- name: deploy
  public: true
  plan:
  - get: trigger
    trigger: true
    passed: [build-project2]
  - get: scripts-source
  - get: source-code
  - task: deploy
    file: scripts-source/tasks/deploy_solution.yml
    params:
      DEVICE_ID: ((device-id))
      USERNAME: ((az-username))
      PASSWORD: ((az-password))
      AZ_AD: ((az-active-directory))


  